id: opecha:P000526
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18847
  title: ཉེན་མེད་ཐོན་སྐྱེད་བྱེད་ཕྱོགས་སྐོར་གྱི་ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ་ཀྱི་བཅའ་ཁྲིམས།
  volume: ''
  author: ''
