id: IAD1CF67F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T04:39:18+00:00'
last_modified: '2022-06-07T12:07:43.202707+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18847
  title: ཉེན་མེད་ཐོན་སྐྱེད་བྱེད་ཕྱོགས་སྐོར་གྱི་ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ་ཀྱི་བཅའ་ཁྲིམས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    A848:
      image_group_id: I8LS18849
      title: Volume 1 of nyen med thon skyed byed phyogs skor gyi krung hwa mi dmangs
        spyi mthun rgyal khab k+mi bca' khrims/
      total_pages: 68
      order: 1
      base_file: A848.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
